### ISSUE TITLE
Creating an express ts project does not result a script and main properties in package.json 

### ISSUE THREAD

**Issue by eliyabar** [naorzr/UniversalBoiler#1]
`{
  "name": "express-ts",
  "version": "1.0.0",
  "dependencies": {
    "cookie-parser": "^1.4.5",
    "express": "^4.17.1",
    "express-pino-logger": "5.0.0"
  },
  "devDependencies": {
    "@types/cookie-parser": "^1.4.2",
    "@types/express-pino-logger": "4.0.2",
    "typescript": "^3.8.3",
    "ts-node": "^8.10.1"
  }
}
`

this is the package.json that was created after generating express ts project.
no run script and no main.
without those, the app isn't runnable.

**Comment by naorzr** [comment]
I published a new version with a new architecture.
now there's an index.ts generated for each project with both ```build``` and ```start``` scripts
